# EarDream Application Configuration

server:
  port: 8080

spring:
  application:
    name: eardream
  
  
  # 프로필별 설정
  profiles:
    active: ${SPRING_PROFILES_ACTIVE}
    
  # Oracle Database 연결 설정
  
  datasource:
    url: jdbc:oracle:thin:@senior_high?TNS_ADMIN=${ORACLE_TNS_ADMIN}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: oracle.jdbc.OracleDriver
    hikari:
      connection-timeout: 20000
      maximum-pool-size: 10
      minimum-idle: 5

# MyBatis 설정
mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.eardream.domain.**.entity
  type-handlers-package: com.eardream.global.config
  configuration:
    map-underscore-to-camel-case: true
    use-generated-keys: true
    default-executor-type: reuse
    lazy-loading-enabled: false
    # 자동 타입 핸들러 등록
    auto-mapping-behavior: full
    # 자동 매핑 시 알 수 없는 컬럼 무시
    auto-mapping-unknown-column-behavior: none

# Logging 설정 (MVP용 간단 설정)
logging:
  level:
    com.eardream: DEBUG
    org.springframework.web: INFO
    org.mybatis: DEBUG
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n"

# JWT 인증 설정
jwt:
  secret: ${JWT_SECRET_KEY}
  access-token-expiration: 3600000    # 1시간 (밀리초)
  refresh-token-expiration: 604800000 # 7일 (밀리초)

# 카카오 OAuth 설정
kakao:
  client-id: ${KAKAO_CLIENT_ID}
  client-secret: ${KAKAO_CLIENT_SECRET}
  redirect-uri: ${KAKAO_REDIRECT_URI}

# 파일 업로드 설정 (EC2 로컬 파일 시스템)
file:
  upload:
    path: ./uploads
    max-size: 10MB

# Actuator 설정 (모니터링 및 헬스체크)
management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics,prometheus
      base-path: /actuator
  endpoint:
    health:
      show-details: when-authorized
      show-components: always
  health:
    oracle:
      enabled: true
    diskspace:
      enabled: true
  info:
    env:
      enabled: true
    java:
      enabled: true
    os:
      enabled: true

---
# 로컬 개발 환경 설정 (H2 in-memory + Oracle 호환 모드)

#spring:
 # config:
  #  activate:
   #   on-profile: local
  #datasource:
   # url: jdbc:h2:mem:eardream;MODE=Oracle;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
   # username: sa
   # password:
   # driver-class-name: org.h2.Driver
  #h2:
   # console:
    #  enabled: true
 # sql:
  #  init:
   #   mode: always */

logging:
  level:
    root: INFO
    com.eardream: DEBUG

# Health 설정 (Oracle Health 체크 비활성화)
management:
  health:
    oracle:
      enabled: false

# 로컬 JWT 시크릿 (64+ 바이트)
jwt:
  secret: localdevsecretlocaldevsecretlocaldevsecretlocaldevsecretlocaldevsecret
  access-token-expiration: 3600000
  refresh-token-expiration: 604800000

---
# 개발 환경 설정
spring:
  config:
    activate:
      on-profile: dev
  
  # 프로덕션용 Oracle 서비스 (고성능)
  datasource:
    url: jdbc:oracle:thin:@senior_high?TNS_ADMIN=${ORACLE_TNS_ADMIN}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    hikari:
      maximum-pool-size: 20
      connection-timeout: 30000
logging:
  level:
    root: INFO
    com.eardream: DEBUG

# 개발 환경 Actuator 설정
management:
  endpoints:
    web:
      exposure:
        include: "*"

---
# 프로덕션 환경 설정
spring:
  config:
    activate:
      on-profile: prod

# 프로덕션용 Oracle 서비스 (고성능)
  datasource:
    url: jdbc:oracle:thin:@senior_high?TNS_ADMIN=${ORACLE_TNS_ADMIN}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    hikari:
      maximum-pool-size: 20
      connection-timeout: 30000

logging:
  level:
    root: WARN
    com.eardream: INFO
  file:
    name: /var/log/eardream/application.log
  logback:
    rollingpolicy:
      max-file-size: 10MB
      max-history: 30
      total-size-cap: 1GB

# 프로덕션 환경 Actuator 설정 (보안 강화)
management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics
  endpoint:
    health:
      show-details: never